
examples:
	@make -C CannonBall
	@make -C MassSpringDamper
	@make -C Orbit

clean:
	@make -C CannonBall clean
	@make -C MassSpringDamper clean
	@make -C Orbit clean

spotless:
	@make -C CannonBall spotless
	@make -C MassSpringDamper spotless
	@make -C Orbit spotless
