
examples:
	@make -C CannonBall
	@make -C BouncyCannonBall
	@make -C MassSpringDamper
	@make -C DefiniteIntegral
	@make -C DoubleIntegral
	@make -C Orbit
	@make -C AsteroidFlyBy

clean:
	@make -C CannonBall clean
	@make -C BouncyCannonBall clean
	@make -C MassSpringDamper clean
	@make -C DefiniteIntegral clean
	@make -C DoubleIntegral clean
	@make -C Orbit clean
	@make -C AsteroidFlyBy clean

spotless:
	@make -C CannonBall spotless
	@make -C BouncyCannonBall spotless
	@make -C MassSpringDamper spotless
	@make -C DefiniteIntegral spotless
	@make -C DoubleIntegral spotless
	@make -C Orbit spotless
	@make -C AsteroidFlyBy spotless
