TRICK_HOME := $(abspath $(dir $(lastword $(MAKEFILE_LIST)))../../..)
include ${TRICK_HOME}/share/trick/makefiles/Makefile.common
include ${TRICK_HOME}/share/trick/makefiles/Makefile.tricklib
-include Makefile_deps
TRICK_CXXFLAGS += -std=c++11
