/**
 * Parses `<sim>/S_sie.resource` (regenerated by every trick-CP/make build) and
 * turns it into typed Python stub classes so Pylance can offer real
 * completion/hover/diagnostics for sim variables (e.g. `ball.state.input.mass`)
 * in input.py/.dr files.
 *
 * File shape (see trick_source/codegen/Interface_Code_Gen/PrintAttributes.cpp
 * and the Java reference parser at
 * trick_source/java/src/main/java/trick/sie/utils/SieResourceDomParser.java):
 *   <class name="X"><member name=".." type=".." units=".." description="..">
 *     <dimension>N</dimension>*</member>*</class>
 *   <enumeration name="X"><pair label ="L" value="V"/></enumeration>
 *   <top_level_object name=".." type=".." alloc_memory_init="0|1"></top_level_object>
 * Inheritance is already flattened by ICG (base members appear inline), `::`
 * is mangled to `__` everywhere, and `>` inside STL template types is left
 * unescaped - so this is a tolerant element/attribute scanner, not a strict
 * XML parser.
 */

export interface SieMember {
  name: string;
  type: string;
  units: string;
  description?: string;
  dims: number[];
}

export interface SieModel {
  classes: Map<string, SieMember[]>;
  enums: Map<string, { label: string; value: string }[]>;
  topLevel: { name: string; type: string }[];
}

function decodeXmlEntities(text: string): string {
  return text
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, '&');
}

function parseAttrs(attrText: string): Record<string, string> {
  const attrs: Record<string, string> = {};
  const re = /([A-Za-z_][\w]*)\s*=\s*"([^"]*)"/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(attrText))) {
    attrs[m[1]] = decodeXmlEntities(m[2]);
  }
  return attrs;
}

// Trick's XML writer (replace_special_chars in AttributesMap.cpp) escapes &,
// ", and < in attribute values, but NOT > - so a member's `type` (STL
// templates like `std__vector<Foo *>`) or free-text `description` ("x > 0",
// "task->base") routinely contains a literal, unescaped `>` inside a quoted
// attribute value. A naive `<member([^>]*?)>` regex would stop at that
// embedded `>` instead of the tag's real end, so the open tag's end must be
// found with quote-aware scanning instead.
function findOpenTagEnd(text: string, from: number): { end: number; selfClosing: boolean } | undefined {
  let inQuote = false;
  for (let i = from; i < text.length; i++) {
    const ch = text[i];
    if (ch === '"') {
      inQuote = !inQuote;
    } else if (!inQuote && ch === '>') {
      return { end: i, selfClosing: text[i - 1] === '/' };
    }
  }
  return undefined;
}

function parseMembers(classBody: string): SieMember[] {
  const members: SieMember[] = [];
  let pos = 0;
  while (true) {
    const start = classBody.indexOf('<member', pos);
    if (start === -1) {
      break;
    }
    const attrsStart = start + '<member'.length;
    const tagEnd = findOpenTagEnd(classBody, attrsStart);
    if (!tagEnd) {
      break;
    }
    const attrsText = classBody.slice(attrsStart, tagEnd.selfClosing ? tagEnd.end - 1 : tagEnd.end);
    const attrs = parseAttrs(attrsText);

    let dims: number[] = [];
    pos = tagEnd.end + 1;
    if (!tagEnd.selfClosing) {
      const closeIdx = classBody.indexOf('</member>', pos);
      if (closeIdx === -1) {
        break;
      }
      const body = classBody.slice(pos, closeIdx);
      const dimRe = /<dimension>(\d+)<\/dimension>/g;
      let d: RegExpExecArray | null;
      while ((d = dimRe.exec(body))) {
        dims.push(parseInt(d[1], 10));
      }
      pos = closeIdx + '</member>'.length;
    }

    if (!attrs.name || !attrs.type) {
      continue;
    }
    members.push({
      name: attrs.name,
      type: attrs.type,
      units: attrs.units ?? '--',
      description: attrs.description,
      dims,
    });
  }
  return members;
}

export function parseSieResource(xml: string): SieModel {
  const classes = new Map<string, SieMember[]>();
  const classRe = /<class\s+name\s*=\s*"([^"]*)"\s*>([\s\S]*?)<\/class>/g;
  let m: RegExpExecArray | null;
  while ((m = classRe.exec(xml))) {
    classes.set(decodeXmlEntities(m[1]), parseMembers(m[2]));
  }

  const enums = new Map<string, { label: string; value: string }[]>();
  const enumRe = /<enumeration\s+name\s*=\s*"([^"]*)"\s*>([\s\S]*?)<\/enumeration>/g;
  while ((m = enumRe.exec(xml))) {
    const pairs: { label: string; value: string }[] = [];
    const pairRe = /<pair\s+label\s*=\s*"([^"]*)"\s+value\s*=\s*"([^"]*)"\s*\/>/g;
    let p: RegExpExecArray | null;
    while ((p = pairRe.exec(m[2]))) {
      pairs.push({ label: decodeXmlEntities(p[1]), value: p[2] });
    }
    enums.set(decodeXmlEntities(m[1]), pairs);
  }

  const topLevel: { name: string; type: string }[] = [];
  const topRe = /<top_level_object\b([^>]*?)>/g;
  while ((m = topRe.exec(xml))) {
    const attrs = parseAttrs(m[1]);
    if (attrs.name && attrs.type) {
      topLevel.push({ name: attrs.name, type: attrs.type });
    }
  }

  return { classes, enums, topLevel };
}

// Trick View's SieResourceDomParser only unwraps vector/deque/array to their
// element type (single template parameter); list/map/set/pair/queue/stack
// are left as opaque leaves since they're irregular (multiple parameters) -
// mirrored here deliberately rather than guessing at a richer scheme.
const UNWRAPPABLE_CONTAINERS = ['std__vector', 'std__deque', 'std__array'];

export function unwrapContainerElementType(type: string): string | undefined {
  for (const container of UNWRAPPABLE_CONTAINERS) {
    if (type.startsWith(`${container}<`) && type.endsWith('>')) {
      let inner = type.slice(container.length + 1, -1).trim();
      // array<T, N> - drop the trailing size argument.
      const comma = inner.indexOf(',');
      if (comma !== -1) {
        inner = inner.slice(0, comma).trim();
      }
      return inner.replace(/\*+$/, '').trim();
    }
  }
  return undefined;
}

const PY_KEYWORDS = new Set([
  'False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break',
  'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally',
  'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal',
  'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield',
]);

function isValidMemberName(name: string): boolean {
  return /^[A-Za-z_]\w*$/.test(name) && !PY_KEYWORDS.has(name);
}

function reachableClasses(model: SieModel): Set<string> {
  const reachable = new Set<string>();
  const visit = (typeName: string): void => {
    const elementType = unwrapContainerElementType(typeName);
    const target = elementType ?? typeName;
    if (reachable.has(target) || !model.classes.has(target)) {
      return;
    }
    reachable.add(target);
    for (const member of model.classes.get(target)!) {
      visit(member.type);
    }
  };
  for (const obj of model.topLevel) {
    visit(obj.type);
  }
  return reachable;
}

/** Maps a member's SIE type string to a Python type reference for the stub. */
function pyType(type: string, dims: number[], model: SieModel, reachable: Set<string>): string {
  let base: string;
  const elementType = unwrapContainerElementType(type);
  if (elementType !== undefined) {
    base = reachable.has(elementType) ? `TrickArray[${elementType}]` : 'TrickArray[Any]';
  } else if (reachable.has(type)) {
    base = type;
  } else if (model.enums.has(type)) {
    base = 'int';
  } else if (type === 'char' && dims.length > 0) {
    // const char*/char[] - treated as a string leaf, not an array of char.
    return 'Any';
  } else {
    // Unknown class, unresolved STL container, or a plain primitive - `Any`
    // deliberately rather than e.g. `float`/`bool`, since input.py commonly
    // does things like `attach_units(...)` or assigns 1/0 to a bool field,
    // which a precise primitive type would flag as an assignment error.
    base = 'Any';
  }
  // Each array dimension beyond the (already-unwrapped) outer container adds
  // another layer of indexing, e.g. a 2-D fixed array.
  const extraDims = elementType !== undefined ? dims.length - 1 : dims.length;
  for (let i = 0; i < extraDims; i++) {
    base = `TrickArray[${base}]`;
  }
  return base;
}

// Member descriptions are free-text C++ comments and can contain anything,
// including quote characters (e.g. a real description reads: Run directory
// name "RUN_<unique_tag>") - a triple-quoted docstring would be unsafe
// (content containing `"""` or ending in `"` breaks it), so this emits a
// single-quoted literal with manual escaping instead. Pyright/Pylance treat
// any bare string-literal statement right after an attribute as its doc
// comment, regardless of quote style.
function pyStringLiteral(text: string): string {
  const escaped = text
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\r?\n/g, '\\n');
  return `'${escaped}'`;
}

const STUB_HEADER = [
  '# Auto-generated by vscode-trick from S_sie.resource. Do not edit by hand -',
  '# rebuild the sim, or run "Trick: Regenerate Python Stubs", instead.',
  'from typing import Any, Generic, Iterator, TypeVar',
  '',
  '_T = TypeVar("_T")',
  '',
  'class TrickArray(Generic[_T]):',
  '    def __getitem__(self, index: int) -> _T: ...',
  '    def __setitem__(self, index: int, value: _T) -> None: ...',
  '    def __len__(self) -> int: ...',
  '    def __iter__(self) -> Iterator[_T]: ...',
  '',
];

/**
 * Emits a .pyi module with one class per SIE class reachable from a
 * top_level_object (the hundreds of unused Trick-framework classes also
 * present in S_sie.resource - from the shared sim_services_classes.resource -
 * are omitted unless something reachable actually references them).
 */
export function generateSieStub(model: SieModel): string {
  const reachable = reachableClasses(model);
  const lines = [...STUB_HEADER];

  for (const className of [...reachable].sort()) {
    lines.push(`class ${className}:`);
    const members = model.classes.get(className) ?? [];
    let emitted = 0;
    for (const member of members) {
      if (!isValidMemberName(member.name)) {
        continue;
      }
      emitted++;
      const type = pyType(member.type, member.dims, model, reachable);
      lines.push(`    ${member.name}: ${type}`);
      const docParts = [member.type, member.units && member.units !== '--' ? `[${member.units}]` : ''];
      const doc = docParts.filter(Boolean).join(' ');
      const descr = member.description ? ` - ${member.description}` : '';
      if (doc || descr) {
        lines.push(`    ${pyStringLiteral(`${doc}${descr}`)}`);
      }
    }
    if (emitted === 0) {
      lines.push('    ...');
    }
    lines.push('');
  }

  return lines.join('\n');
}
