#include "../include/test13.h"

void test13_init(TEST13 *T) {
T->c_types.c = 'u' ;
T->c_types.uc = 'c';
T->c_types.cp = strdup(".gnirts tseT") ;
T->c_types.s++ ;
T->c_types.us++ ;
T->c_types.i++ ;
T->c_types.ui++ ;
T->c_types.l++ ;
T->c_types.ul++ ;
T->c_types.f++ ;
T->c_types.d++ ;
T->c_types.ll++ ;
T->c_types.ull++ ;

T->c_array_types.ca[0][0][0]  = 'p' ;
T->c_array_types.ca[0][0][1]  = 'o' ;
T->c_array_types.ca[0][1][0]  = 'n' ;
T->c_array_types.ca[0][1][1]  = 'm' ;
T->c_array_types.ca[1][0][0]  = 'l' ;
T->c_array_types.ca[1][0][1]  = 'k' ;
T->c_array_types.ca[1][1][0]  = 'j' ;
T->c_array_types.ca[1][1][1]  = 'i' ;
T->c_array_types.uca[0][0][0] = 'h' ;
T->c_array_types.uca[0][0][1] = 'g' ;
T->c_array_types.uca[0][1][0] = 'f' ;
T->c_array_types.uca[0][1][1] = 'e' ;
T->c_array_types.uca[1][0][0] = 'd' ;
T->c_array_types.uca[1][0][1] = 'c' ;
T->c_array_types.uca[1][1][0] = 'b' ;
T->c_array_types.uca[1][1][1] = 'a' ;
T->c_array_types.sa[0][0][0]++ ;
T->c_array_types.sa[0][0][1]++ ;
T->c_array_types.sa[0][1][0]++ ;
T->c_array_types.sa[0][1][1]++ ;
T->c_array_types.sa[1][0][0]++ ;
T->c_array_types.sa[1][0][1]++ ;
T->c_array_types.sa[1][1][0]++ ;
T->c_array_types.sa[1][1][1]++ ;
T->c_array_types.usa[0][0][0]++ ;
T->c_array_types.usa[0][0][1]++ ;
T->c_array_types.usa[0][1][0]++ ;
T->c_array_types.usa[0][1][1]++ ;
T->c_array_types.usa[1][0][0]++ ;
T->c_array_types.usa[1][0][1]++ ;
T->c_array_types.usa[1][1][0]++ ;
T->c_array_types.usa[1][1][1]++ ;
T->c_array_types.ia[0][0][0]++ ;
T->c_array_types.ia[0][0][1]++ ;
T->c_array_types.ia[0][1][0]++ ;
T->c_array_types.ia[0][1][1]++ ;
T->c_array_types.ia[1][0][0]++ ;
T->c_array_types.ia[1][0][1]++ ;
T->c_array_types.ia[1][1][0]++ ;
T->c_array_types.ia[1][1][1]++ ;
T->c_array_types.uia[0][0][0]++ ;
T->c_array_types.uia[0][0][1]++ ;
T->c_array_types.uia[0][1][0]++ ;
T->c_array_types.uia[0][1][1]++ ;
T->c_array_types.uia[1][0][0]++ ;
T->c_array_types.uia[1][0][1]++ ;
T->c_array_types.uia[1][1][0]++ ;
T->c_array_types.uia[1][1][1]++ ;
T->c_array_types.la[0][0][0]++ ;
T->c_array_types.la[0][0][1]++ ;
T->c_array_types.la[0][1][0]++ ;
T->c_array_types.la[0][1][1]++ ;
T->c_array_types.la[1][0][0]++ ;
T->c_array_types.la[1][0][1]++ ;
T->c_array_types.la[1][1][0]++ ;
T->c_array_types.la[1][1][1]++ ;
T->c_array_types.ula[0][0][0]++ ;
T->c_array_types.ula[0][0][1]++ ;
T->c_array_types.ula[0][1][0]++ ;
T->c_array_types.ula[0][1][1]++ ;
T->c_array_types.ula[1][0][0]++ ;
T->c_array_types.ula[1][0][1]++ ;
T->c_array_types.ula[1][1][0]++ ;
T->c_array_types.ula[1][1][1]++ ;
T->c_array_types.fa[0][0][0]++ ;
T->c_array_types.fa[0][0][1]++ ;
T->c_array_types.fa[0][1][0]++ ;
T->c_array_types.fa[0][1][1]++ ;
T->c_array_types.fa[1][0][0]++ ;
T->c_array_types.fa[1][0][1]++ ;
T->c_array_types.fa[1][1][0]++ ;
T->c_array_types.fa[1][1][1]++ ;
T->c_array_types.da[0][0][0]++ ;
T->c_array_types.da[0][0][1]++ ;
T->c_array_types.da[0][1][0]++ ;
T->c_array_types.da[0][1][1]++ ;
T->c_array_types.da[1][0][0]++ ;
T->c_array_types.da[1][0][1]++ ;
T->c_array_types.da[1][1][0]++ ;
T->c_array_types.da[1][1][1]++ ;
T->c_array_types.lla[0][0][0]++ ;
T->c_array_types.lla[0][0][1]++ ;
T->c_array_types.lla[0][1][0]++ ;
T->c_array_types.lla[0][1][1]++ ;
T->c_array_types.lla[1][0][0]++ ;
T->c_array_types.lla[1][0][1]++ ;
T->c_array_types.lla[1][1][0]++ ;
T->c_array_types.lla[1][1][1]++ ;
T->c_array_types.ulla[0][0][0]++ ;
T->c_array_types.ulla[0][0][1]++ ;
T->c_array_types.ulla[0][1][0]++ ;
T->c_array_types.ulla[0][1][1]++ ;
T->c_array_types.ulla[1][0][0]++ ;
T->c_array_types.ulla[1][0][1]++ ;
T->c_array_types.ulla[1][1][0]++ ;
T->c_array_types.ulla[1][1][1]++ ;

T->c_pointer_types.cpp[0][0][0]   = strdup("eno") ;
T->c_pointer_types.cpp[0][0][1]   = strdup("owt") ;
T->c_pointer_types.cpp[0][1][0]   = strdup("eerht") ;
T->c_pointer_types.cpp[0][1][1]   = strdup("ruof") ;
T->c_pointer_types.cpp[1][0][0]   = strdup("evif") ;
T->c_pointer_types.cpp[1][0][1]   = strdup("xis") ;
T->c_pointer_types.cpp[1][1][0]   = strdup("neves") ;
T->c_pointer_types.cpp[1][1][1]   = strdup("thgie") ;
T->c_pointer_types.ucpp[0][0][0]  = 'h' ; 
T->c_pointer_types.ucpp[0][0][1]  = 'g' ;
T->c_pointer_types.ucpp[0][1][0]  = 'f' ;
T->c_pointer_types.ucpp[0][1][1]  = 'e' ;
T->c_pointer_types.ucpp[1][0][0]  = 'd' ;
T->c_pointer_types.ucpp[1][0][1]  = 'c' ;
T->c_pointer_types.ucpp[1][1][0]  = 'b' ;
T->c_pointer_types.ucpp[1][1][1]  = 'a' ;
T->c_pointer_types.spp[0][0][0]++ ;
T->c_pointer_types.spp[0][0][1]++ ;
T->c_pointer_types.spp[0][1][0]++ ;
T->c_pointer_types.spp[0][1][1]++ ;
T->c_pointer_types.spp[1][0][0]++ ;
T->c_pointer_types.spp[1][0][1]++ ;
T->c_pointer_types.spp[1][1][0]++ ;
T->c_pointer_types.spp[1][1][1]++ ;
T->c_pointer_types.uspp[0][0][0]++ ;
T->c_pointer_types.uspp[0][0][1]++ ;
T->c_pointer_types.uspp[0][1][0]++ ;
T->c_pointer_types.uspp[0][1][1]++ ;
T->c_pointer_types.uspp[1][0][0]++ ;
T->c_pointer_types.uspp[1][0][1]++ ;
T->c_pointer_types.uspp[1][1][0]++ ;
T->c_pointer_types.uspp[1][1][1]++ ;
T->c_pointer_types.ipp[0][0][0]++ ;
T->c_pointer_types.ipp[0][0][1]++ ;
T->c_pointer_types.ipp[0][1][0]++ ;
T->c_pointer_types.ipp[0][1][1]++ ;
T->c_pointer_types.ipp[1][0][0]++ ;
T->c_pointer_types.ipp[1][0][1]++ ;
T->c_pointer_types.ipp[1][1][0]++ ;
T->c_pointer_types.ipp[1][1][1]++ ;
T->c_pointer_types.uipp[0][0][0]++ ;
T->c_pointer_types.uipp[0][0][1]++ ;
T->c_pointer_types.uipp[0][1][0]++ ;
T->c_pointer_types.uipp[0][1][1]++ ;
T->c_pointer_types.uipp[1][0][0]++ ;
T->c_pointer_types.uipp[1][0][1]++ ;
T->c_pointer_types.uipp[1][1][0]++ ;
T->c_pointer_types.uipp[1][1][1]++ ;
T->c_pointer_types.lpp[0][0][0]++ ;
T->c_pointer_types.lpp[0][0][1]++ ;
T->c_pointer_types.lpp[0][1][0]++ ;
T->c_pointer_types.lpp[0][1][1]++ ;
T->c_pointer_types.lpp[1][0][0]++ ;
T->c_pointer_types.lpp[1][0][1]++ ;
T->c_pointer_types.lpp[1][1][0]++ ;
T->c_pointer_types.lpp[1][1][1]++ ;
T->c_pointer_types.ulpp[0][0][0]++ ;
T->c_pointer_types.ulpp[0][0][1]++ ;
T->c_pointer_types.ulpp[0][1][0]++ ;
T->c_pointer_types.ulpp[0][1][1]++ ;
T->c_pointer_types.ulpp[1][0][0]++ ;
T->c_pointer_types.ulpp[1][0][1]++ ;
T->c_pointer_types.ulpp[1][1][0]++ ;
T->c_pointer_types.ulpp[1][1][1]++ ;
T->c_pointer_types.fpp[0][0][0]++ ;
T->c_pointer_types.fpp[0][0][1]++ ;
T->c_pointer_types.fpp[0][1][0]++ ;
T->c_pointer_types.fpp[0][1][1]++ ;
T->c_pointer_types.fpp[1][0][0]++ ;
T->c_pointer_types.fpp[1][0][1]++ ;
T->c_pointer_types.fpp[1][1][0]++ ;
T->c_pointer_types.fpp[1][1][1]++ ;
T->c_pointer_types.dpp[0][0][0]++ ;
T->c_pointer_types.dpp[0][0][1]++ ;
T->c_pointer_types.dpp[0][1][0]++ ;
T->c_pointer_types.dpp[0][1][1]++ ;
T->c_pointer_types.dpp[1][0][0]++ ;
T->c_pointer_types.dpp[1][0][1]++ ;
T->c_pointer_types.dpp[1][1][0]++ ;
T->c_pointer_types.dpp[1][1][1]++ ;
T->c_pointer_types.llpp[0][0][0]++ ;
T->c_pointer_types.llpp[0][0][1]++ ;
T->c_pointer_types.llpp[0][1][0]++ ;
T->c_pointer_types.llpp[0][1][1]++ ;
T->c_pointer_types.llpp[1][0][0]++ ;
T->c_pointer_types.llpp[1][0][1]++ ;
T->c_pointer_types.llpp[1][1][0]++ ;
T->c_pointer_types.llpp[1][1][1]++ ;
T->c_pointer_types.ullpp[0][0][0]++ ;
T->c_pointer_types.ullpp[0][0][1]++ ;
T->c_pointer_types.ullpp[0][1][0]++ ;
T->c_pointer_types.ullpp[0][1][1]++ ;
T->c_pointer_types.ullpp[1][0][0]++ ;
T->c_pointer_types.ullpp[1][0][1]++ ;
T->c_pointer_types.ullpp[1][1][0]++ ;
T->c_pointer_types.ullpp[1][1][1]++ ;

T->c_mixed_types.cpa[0][0][0]   = strdup("eno") ;
T->c_mixed_types.cpa[0][0][1]   = strdup("owt") ;
T->c_mixed_types.cpa[0][1][0]   = strdup("eerht") ;
T->c_mixed_types.cpa[0][1][1]   = strdup("ruof") ;
T->c_mixed_types.cpa[1][0][0]   = strdup("evif") ;
T->c_mixed_types.cpa[1][0][1]   = strdup("xis") ;
T->c_mixed_types.cpa[1][1][0]   = strdup("neves") ;
T->c_mixed_types.cpa[1][1][1]   = strdup("thgie") ;
T->c_mixed_types.ucpa[0][0][0]  = 'h' ;
T->c_mixed_types.ucpa[0][0][1]  = 'g' ;
T->c_mixed_types.ucpa[0][1][0]  = 'f' ;
T->c_mixed_types.ucpa[0][1][1]  = 'e' ;
T->c_mixed_types.ucpa[1][0][0]  = 'd' ;
T->c_mixed_types.ucpa[1][0][1]  = 'c' ;
T->c_mixed_types.ucpa[1][1][0]  = 'b' ;
T->c_mixed_types.ucpa[1][1][1]  = 'a' ;
T->c_mixed_types.spa[0][0][0]++ ;
T->c_mixed_types.spa[0][0][1]++ ;
T->c_mixed_types.spa[0][1][0]++ ;
T->c_mixed_types.spa[0][1][1]++ ;
T->c_mixed_types.spa[1][0][0]++ ;
T->c_mixed_types.spa[1][0][1]++ ;
T->c_mixed_types.spa[1][1][0]++ ;
T->c_mixed_types.spa[1][1][1]++ ;
T->c_mixed_types.uspa[0][0][0]++ ;
T->c_mixed_types.uspa[0][0][1]++ ;
T->c_mixed_types.uspa[0][1][0]++ ;
T->c_mixed_types.uspa[0][1][1]++ ;
T->c_mixed_types.uspa[1][0][0]++ ;
T->c_mixed_types.uspa[1][0][1]++ ;
T->c_mixed_types.uspa[1][1][0]++ ;
T->c_mixed_types.uspa[1][1][1]++ ;
T->c_mixed_types.ipa[0][0][0]++ ;
T->c_mixed_types.ipa[0][0][1]++ ;
T->c_mixed_types.ipa[0][1][0]++ ;
T->c_mixed_types.ipa[0][1][1]++ ;
T->c_mixed_types.ipa[1][0][0]++ ;
T->c_mixed_types.ipa[1][0][1]++ ;
T->c_mixed_types.ipa[1][1][0]++ ;
T->c_mixed_types.ipa[1][1][1]++ ;
T->c_mixed_types.uipa[0][0][0]++ ;
T->c_mixed_types.uipa[0][0][1]++ ;
T->c_mixed_types.uipa[0][1][0]++ ;
T->c_mixed_types.uipa[0][1][1]++ ;
T->c_mixed_types.uipa[1][0][0]++ ;
T->c_mixed_types.uipa[1][0][1]++ ;
T->c_mixed_types.uipa[1][1][0]++ ;
T->c_mixed_types.uipa[1][1][1]++ ;
T->c_mixed_types.lpa[0][0][0]++ ;
T->c_mixed_types.lpa[0][0][1]++ ;
T->c_mixed_types.lpa[0][1][0]++ ;
T->c_mixed_types.lpa[0][1][1]++ ;
T->c_mixed_types.lpa[1][0][0]++ ;
T->c_mixed_types.lpa[1][0][1]++ ;
T->c_mixed_types.lpa[1][1][0]++ ;
T->c_mixed_types.lpa[1][1][1]++ ;
T->c_mixed_types.ulpa[0][0][0]++ ;
T->c_mixed_types.ulpa[0][0][1]++ ;
T->c_mixed_types.ulpa[0][1][0]++ ;
T->c_mixed_types.ulpa[0][1][1]++ ;
T->c_mixed_types.ulpa[1][0][0]++ ;
T->c_mixed_types.ulpa[1][0][1]++ ;
T->c_mixed_types.ulpa[1][1][0]++ ;
T->c_mixed_types.ulpa[1][1][1]++ ;
T->c_mixed_types.fpa[0][0][0]++ ;
T->c_mixed_types.fpa[0][0][1]++ ;
T->c_mixed_types.fpa[0][1][0]++ ;
T->c_mixed_types.fpa[0][1][1]++ ;
T->c_mixed_types.fpa[1][0][0]++ ;
T->c_mixed_types.fpa[1][0][1]++ ;
T->c_mixed_types.fpa[1][1][0]++ ;
T->c_mixed_types.fpa[1][1][1]++ ;
T->c_mixed_types.dpa[0][0][0]++ ;
T->c_mixed_types.dpa[0][0][1]++ ;
T->c_mixed_types.dpa[0][1][0]++ ;
T->c_mixed_types.dpa[0][1][1]++ ;
T->c_mixed_types.dpa[1][0][0]++ ;
T->c_mixed_types.dpa[1][0][1]++ ;
T->c_mixed_types.dpa[1][1][0]++ ;
T->c_mixed_types.dpa[1][1][1]++ ;
T->c_mixed_types.llpa[0][0][0]++ ;
T->c_mixed_types.llpa[0][0][1]++ ;
T->c_mixed_types.llpa[0][1][0]++ ;
T->c_mixed_types.llpa[0][1][1]++ ;
T->c_mixed_types.llpa[1][0][0]++ ;
T->c_mixed_types.llpa[1][0][1]++ ;
T->c_mixed_types.llpa[1][1][0]++ ;
T->c_mixed_types.llpa[1][1][1]++ ;
T->c_mixed_types.ullpa[0][0][0]++ ;
T->c_mixed_types.ullpa[0][0][1]++ ;
T->c_mixed_types.ullpa[0][1][0]++ ;
T->c_mixed_types.ullpa[0][1][1]++ ;
T->c_mixed_types.ullpa[1][0][0]++ ; 
T->c_mixed_types.ullpa[1][0][1]++ ;
T->c_mixed_types.ullpa[1][1][0]++ ;
T->c_mixed_types.ullpa[1][1][1]++ ;

}
