include $(dir $(lastword $(MAKEFILE_LIST)))../../../share/trick/makefiles/Makefile.common
include ${TRICK_HOME}/share/trick/makefiles/Makefile.tricklib
TRICK_CFLAGS += -g -Wall -Wextra -Werror
TRICK_CXXFLAGS += -g -std=c++11 -Wall -Wextra -Werror
-include Makefile_deps
