
include ${TRICK_HOME}/share/trick/makefiles/Makefile.common
include ${TRICK_HOME}/share/trick/makefiles/Makefile.tricklib
-include Makefile_deps

#ifeq ($(USE_ER7_UTILS_INTEGRATORS), 1)
#trick:
#	$(MAKE) -C er7_algorithms
#else
#trick:
#	$(MAKE) -C trick_algorithms
#endif

