# Run in `cmake -P` script mode after a trick-ICG -sim_services run has
# populated IO_SRC_DIR with a flat set of io_<header-basename>.cpp files (plus
# class_map.cpp). Partitions that flat list into TRICK_IO_SOURCES (bundled
# into libtrick.a) and ER7_IO_SOURCES (bundled into liber7_utils.a), matching
# the historical split PrintAttributes::createIOFileName performs by
# inspecting each header's source path — a distinction lost once ICG is
# invoked with an explicit `-o` (see CMAKE_MIGRATION_PLAN.md Part C, Phase 2
# risk R1/R7 write-up). Reconstructed here by checking whether a header with
# a matching basename exists anywhere under ER7_UTILS_SRC_DIR; basenames are
# verified unique across the whole tree (no collisions as of this writing).
#
# Required -D arguments: IO_SRC_DIR, ER7_UTILS_SRC_DIR, OUTPUT_FILE

if(NOT IO_SRC_DIR OR NOT ER7_UTILS_SRC_DIR OR NOT OUTPUT_FILE)
    message(FATAL_ERROR "GenerateIOSrcList.cmake requires -DIO_SRC_DIR=, -DER7_UTILS_SRC_DIR=, -DOUTPUT_FILE=")
endif()

file(GLOB _tr_io_files "${IO_SRC_DIR}/io_*.cpp")
file(GLOB_RECURSE _tr_er7_headers "${ER7_UTILS_SRC_DIR}/*.hh" "${ER7_UTILS_SRC_DIR}/*.h")

set(_tr_er7_basenames)
foreach(_hdr ${_tr_er7_headers})
    get_filename_component(_stem "${_hdr}" NAME_WE)
    list(APPEND _tr_er7_basenames "${_stem}")
endforeach()

set(_tr_trick_io_sources)
set(_tr_er7_io_sources)
foreach(_cpp ${_tr_io_files})
    get_filename_component(_name "${_cpp}" NAME_WE)
    # NOT string(REGEX REPLACE "^io_" ...): CMake's regex replace strips
    # repeated leading matches (e.g. turns "io_io_alloc" into "alloc" instead
    # of "io_alloc"), silently misrouting io_io_alloc.cpp (from
    # include/trick/io_alloc.h) into the er7_utils archive. Every io_*.cpp
    # name has exactly one "io_" prefix by construction (PrintAttributes.cpp:
    # base_name = "io_" + stem), so a plain substring removal is correct.
    string(SUBSTRING "${_name}" 3 -1 _stem)
    list(FIND _tr_er7_basenames "${_stem}" _tr_idx)
    if(_tr_idx GREATER -1)
        list(APPEND _tr_er7_io_sources "${_cpp}")
    else()
        list(APPEND _tr_trick_io_sources "${_cpp}")
    endif()
endforeach()

file(WRITE "${OUTPUT_FILE}"
"# Auto-generated by GenerateIOSrcList.cmake — do not edit.
set(TRICK_IO_SOURCES ${_tr_trick_io_sources} \"${IO_SRC_DIR}/class_map.cpp\")
set(ER7_IO_SOURCES ${_tr_er7_io_sources})
")
