.TH trick-gxplot 1 "August 1, 2016" "Trick" "Trick User's Manual"
.SH NAME
trick-gxplot \- Trick plot utility using GNUPlot
.SH SYNOPSIS
\fBtrick-gxplot\fP <session_file>.xml
.SH DESCRIPTION
trick-gxplot uses GNUPlot to plot Trick simulation recorded data.
The input to trick-gxplot is a session file that lists the simulation directories
to plot, the layout of the plots, and the variables to place in each plot.

The session files are created through the \fBtrick-dp\fP command.  trick-gxplot may
be brought up directly through the \fBtrick-dp\fP GUI.
.SH FILES
.TP
\fI/tmp/Session_<user>.xml\fP
The default session file name created by \fBtrick-dp\fP used as an arugment to
start \fBtrick-gxplot\fP
.SH "SEE ALSO"
\fBtrick-dp\fP(1), \fBtrick-qp\fP(1)
.PP
All Trick model developers and users should go through the tutorial found
in the \fITrick Simulation Environment User Training Materials\fP.
The canonical reference for all Trick commands, files and utilities is the
\fITrick Simulation Environment User's Guide\fP.  Information specific to a
given release of Trick tools is contained in the \fITrick Simulation
Environment Version Description\fP for that release.
.SH HISTORY
1991-2000 : \fBgplot\fP originally written in C by Rob Bailey and Eddie Paddock

2001-2009 : \fBgplot\fP ported to C++ Keith Vetter

2010-present : \fBtrick-gxplot\fP rewritten by John Penn

