.TH trick-version 1 "August 2, 2016" "Trick" "Trick User's Manual"
.SH NAME
trick-version \- Trick Version
.SH SYNOPSIS
\fBtrick-version\fP[OPTIONS]...
.SH DESCRIPTION
The Trick Version prints the current version of Trick. Wee!  Without arguments
trick-version prints the full Trick version.
.TP
\fB-f, -full, -v, -version\fP
Prints the full version including year (major), minor, and patchlevel
.TP
\fB-m, -minor\fP
Prints the minor version
.TP
\fB-y, -year\fP
Prints the year (major) version
.SH "SEE ALSO"
All Trick model developers and users should go through the tutorial found
in the \fITrick Simulation Environment User Training Materials\fP.
The canonical reference for all Trick coversionands, files and utilities is the
\fITrick Simulation Environment User's Guide\fP.  Information specific to a
given release of Trick tools is contained in the \fITrick Simulation
Environment Version Description\fP for that release.
.SH HISTORY
2003-present : \fBtrick-version\fP written in Perl by Alex Lin

