.TH trick-killsim 1 "August 1, 2016" "Trick" "Trick User's Manual"
.SH NAME
trick-killsim \- Kill Trick simulations
.SH SYNOPSIS
\fBtrick-killsim\fP
.SH DESCRIPTION
\fBtrick-killsim\fP is a bourne shell script whick kills all Trick simulation processes for
a user.
.SH "SEE ALSO"
All Trick model developers and users should go through the tutorial found
in the \fITrick Simulation Environment User Training Materials\fP.
The canonical reference for all Trick commands, files and utilities is the
\fITrick Simulation Environment User's Guide\fP.  Information specific to a
given release of Trick tools is contained in the \fITrick Simulation
Environment Version Description\fP for that release.
.SH HISTORY
1997-present : \fBtrick-killsim\fP was written by Greg Alexander

