.TH trick-sniffer 1 "August 1, 2016" "Trick" "Trick User's Manual"
.SH NAME
trick-sniffer \- Trick Simulation Sniffer
.SH SYNOPSIS
\fBtrick-sniffer\fP
.SH DESCRIPTION
The Trick Simulation Sniffer listens for simulation broadcast messages emmitted by all simulations.
The sniffer lists the simulations and provides the capability to connect a \fBtrick-simcontrol\fP
, \fBtrick-tv\fP, \fBtrick-mtv\fP, or \fBtrick-mm\fP to the simulation.
.SH "SEE ALSO"
\fBtrick-mm\fP(1), \fBtrick-mtv\fP(1), \fBtrick-simcontrol\fP(1), \fBtrick-tv\fP(1)
.PP
All Trick model developers and users should go through the tutorial found
in the \fITrick Simulation Environment User Training Materials\fP.
The canonical reference for all Trick commands, files and utilities is the
\fITrick Simulation Environment User's Guide\fP.  Information specific to a
given release of Trick tools is contained in the \fITrick Simulation
Environment Version Description\fP for that release.
.SH HISTORY

2007-2012 : \fBtrick-sniffer\fP written in Tcl/TK by Alex Lin

2013-present : \fBtrick-sniffer\fP written in Java by Hong Chen

