.TH trick-mtv 1 "August 1, 2016" "Trick" "Trick User's Manual"
.SH NAME
trick-mtv \- Trick Malfunctions Trick Viewer
.SH SYNOPSIS
\fBtrick-mtv\fP
.SH DESCRIPTION
The Trick Malfunctions Trick Viewer (mtv) displays all malfunctions and events defined in
a simulation.  The mtv connects to the simulation through the simulation
variable server.  Users may create, modify, trigger, and disable malfunctions
within the simulation using mtv.
.SH "SEE ALSO"
All Trick model developers and users should go through the tutorial found
in the \fITrick Simulation Environment User Training Materials\fP.
The canonical reference for all Trick comtvands, files and utilities is the
\fITrick Simulation Environment User's Guide\fP.  Information specific to a
given release of Trick tools is contained in the \fITrick Simulation
Environment Version Description\fP for that release.
.SH HISTORY
2013-present : \fBtrick-mtv\fP written in Java by Danny Strauss

