.TH trick-mm 1 "August 1, 2016" "Trick" "Trick User's Manual"
.SH NAME
trick-mm \- Trick Monte Monitor
.SH SYNOPSIS
\fBtrick-mm\fP
.SH DESCRIPTION
The Trick Monte Monitor diplays the status of a running Trick monte carlo simulation.
The Monte Monitor connects to the Trick monte carlo master simulation through the simulation
variable server.
.SH "SEE ALSO"
All Trick model developers and users should go through the tutorial found
in the \fITrick Simulation Environment User Training Materials\fP.
The canonical reference for all Trick commands, files and utilities is the
\fITrick Simulation Environment User's Guide\fP.  Information specific to a
given release of Trick tools is contained in the \fITrick Simulation
Environment Version Description\fP for that release.
.SH HISTORY
2013-present : \fBtrick-mm\fP written in Java by Danny Strauss

