.TH trick-tv 1 "August 2, 2016" "Trick" "Trick User's Manual"
.SH NAME
trick-tv \- Trick Viewer
.SH SYNOPSIS
\fBtrick-tv\fP
.SH DESCRIPTION
The Trick Viewer (tv) is a graphical user interface that allows users to
view and modify Trick managed variables in a simulation while it is running.
It also provides for the launching of integrated strip charts and can save and
restore lists of variables and their associated strip charts.
.SH "SEE ALSO"
All Trick model developers and users should go through the tutorial found
in the \fITrick Simulation Environment User Training Materials\fP.
The canonical reference for all Trick cotvands, files and utilities is the
\fITrick Simulation Environment User's Guide\fP.  Information specific to a
given release of Trick tools is contained in the \fITrick Simulation
Environment Version Description\fP for that release.
.SH HISTORY
2001-2010 : \fBtrick_tv\fP written in Tcl/TK by Keith Vetter

2013-present : \fBtrick-tv\fP ported to Java by Derek Bankieris

