# Go up to parent directory and run make from there
default:
	cd .. ; $(MAKE)
ICG:
	cd .. ; $(MAKE) ICG
depend:
	cd .. ; $(MAKE) depend
io_clean:
	cd .. ; $(MAKE) io_clean
catalog_clean:
	cd .. ; $(MAKE) catalog_clean
clean:
	cd .. ; $(MAKE) clean
real_clean:
	cd .. ; $(MAKE) real_clean
