
include ${TRICK_HOME}/share/trick/makefiles/Makefile.common

.NOTPARALLEL: all test

export TRICK_ICG_EXCLUDE

# Use /bin/bash as the shell so we can use PIPESTATUS
SHELL = /bin/bash

ifeq ($(MAKECMDGOALS), debug)
 TRICK_CPFLAGS += --debug
endif

all : ${TRICK_LIB_DIR}/libtrick.a build/Makefile_sim
	@/bin/cp ${TRICK_HOME}/share/trick/MAKE_out_header.txt build/MAKE_out
	@$(MAKE) --no-print-directory -f build/Makefile_sim ICG 2>&1 | tee -a build/MAKE_out ; exit $${PIPESTATUS[0]}
	@$(MAKE) --no-print-directory -f build/Makefile_sim convert_swig 2>&1 | tee -a build/MAKE_out ; exit $${PIPESTATUS[0]}
	@$(MAKE) --no-print-directory -f build/Makefile_sim all 2>&1 | tee -a build/MAKE_out ; exit $${PIPESTATUS[0]}

test : ${TRICK_LIB_DIR}/libtrick.a build/Makefile_sim
	@/bin/cp ${TRICK_HOME}/share/trick/MAKE_out_header.txt build/MAKE_out
	@$(MAKE) --no-print-directory -f build/Makefile_sim ICG 2>&1 | tee -a build/MAKE_out ; exit $${PIPESTATUS[0]}
	@$(MAKE) --no-print-directory -f build/Makefile_sim convert_swig 2>&1 | tee -a build/MAKE_out ; exit $${PIPESTATUS[0]}
	@$(MAKE) --no-print-directory -f build/Makefile_sim test_all 2>&1 | tee -a build/MAKE_out ; exit $${PIPESTATUS[0]}

build:
	mkdir $@

debug : all

${TRICK_LIB_DIR}/libtrick.a:
	@echo "Cannot find $@.  Please build Trick for this platfrom"
	@exit -1

build/Makefile_sim: S_define | build
	@${TRICK_HOME}/$(LIBEXEC)/trick/configuration_processor $(TRICK_CPFLAGS)

model_dirs:
	@${TRICK_HOME}/$(LIBEXEC)/trick/configuration_processor -z

sie ICG force_ICG convert_swig S_define_exp:
	@if [ -f build/Makefile_sim ] ; then $(MAKE) --no-print-directory -f build/Makefile_sim $@ ; else echo "No build/Makefile_sim found" ; fi

help:
	@ echo -e "\
Simulation make options:\n\
    make [debug] [TRICK_VERBOSE_BUILD=1] - Makes everything: S_main and S_sie.resource\n\
    make model_dirs              - Lists model directories use to build simulation\n\
    make sie                     - Builds the S_sie.resource file.\n\
    make clean                   - Removes all object files in simulation directory\n\
    make spotless                - Performs a clean\n\
    make apocalypse              - Performs a clean"

tidy:
	-rm -f S_sie.resource
	-rm -f DP_Product/DP_rt_frame DP_Product/DP_rt_itimer
	-rm -f DP_Product/DP_rt_jobs DP_Product/DP_rt_timeline DP_Product/DP_mem_stats
	-rm -f S_main* T_main*

clean: tidy
	-rm -rf Default_data S_default.dat
	rm -f S_source.hh
	rm -rf build
	-rm -rf trick
	@ echo "Removed build directory"

spotless: clean

apocalypse: clean
	@echo "[31mI love the smell of napalm in the morning[0m"


# Dependencies to other files that may cause a re-CP
-include build/S_define.deps

