ifneq ($(TRICKIFY_S_OVERRIDES),)
	include $(TRICKIFY_S_OVERRIDES)
endif


#gcc $(TRICKIFY_SRC_MAKE_ARGS) $(TRICKIFY_CXX_FLAGS) $(TRICK_CXXFLAGS) $(TRICK_CFLAGS) $(TRICK_LDFLAGS) -c $(TRICKIFY_SRC_MAKE_SRC) -o $(TRICKIFY_SRC_MAKE_OBJ)
#g++ $(TRICKIFY_SRC_MAKE_ARGS) $(TRICKIFY_CXX_FLAGS) $(TRICK_CXXFLAGS) $(TRICK_CFLAGS) $(TRICK_LDFLAGS) -c $(TRICKIFY_SRC_MAKE_SRC) -o $(TRICKIFY_SRC_MAKE_OBJ)

.PHONY: C
C: 
	gcc $(TRICKIFY_SRC_MAKE_ARGS) $(TRICKIFY_CXX_FLAGS) $(TRICK_CXXFLAGS) $(TRICK_CFLAGS) $(TRICK_SFLAGS) -c $(TRICKIFY_SRC_MAKE_SRC) -o $(TRICKIFY_SRC_MAKE_OBJ)


.PHONY: CPP
CPP: 
	g++ $(TRICKIFY_SRC_MAKE_ARGS) $(TRICKIFY_CXX_FLAGS) $(TRICK_CXXFLAGS) $(TRICK_CFLAGS) $(TRICK_SFLAGS) -c $(TRICKIFY_SRC_MAKE_SRC) -o $(TRICKIFY_SRC_MAKE_OBJ)
