# CP found at /users/alin/trick_dev/trunk/bin

ifndef TRICK_HOME
    export TRICK_HOME := /users/alin/trick_dev/trunk
endif

include ${TRICK_HOME}/makefiles/Makefile.common
include ${TRICK_HOME}/makefiles/Makefile.sim
-include S_overrides.mk

