# Configuration file for VIRGO to consume related to this simulation configuration
 start_mode: PAUSED
 description: SIM_satellite visualization
 background_color: [0.0, 0.0, 0.05]
 highlight_color: [0.9, 0.9, 0.9]
 playback_speeds: [1.0, 5.0, 10.0, 20.0, 50.0, 100.0]
 playback_speed: 5.0
 starfield: 0
 recorded_data:  # Logged data to read into virgo during init
  time: 
    group: Satellite            # Data recording group
    var: sys.exec.out.time   # Name given to time (first) column
  # Everything else is a data alias for logged data variables
  sat_pos: 
    group: Satellite            # Data recording group
    var: dyn.satellite.pos[0-2] # Data recording variable
  sat_vel: 
    group: Satellite            # Data recording group
    var: dyn.satellite.vel[0-2] # Data recording variable
  sat_rot: 
    group: Satellite                # Data recording group
    var: dyn.satellite.R[0-2][0-2]  # Data recording variable
 actors:
   earth: 
     mesh: PREFAB:earth
     scale: 1.0             # Size multiplier
     pos:   [0.0, 0.0, 0.0] # initial position offset in scene
     pyr:   [0.0, 0.0, 0.0] # pitch-yaw-roll rotation offset, applied after pos:
     pickable: 0
     driven_by: 0 # Not driven by any logged variable
   satellite:
     mesh: PREFAB:cube         # Size multiplier
     scale: 100.0
     pos: [0.0, 0.0, 0.0]
     pyr: [0.0, 0.0, 90.0]
     color: [0.6, 0.6, 0.6]
     pickable:   # If given, this actor is pickable with the mouse
       focus: 1  # On pick, focus camera on actor
       hud:      # 
         World position: sat_pos
         Initial vel: sat_vel
     trail: [0.0, 1.0, 0.0] #  # Color of trail
     driven_by:  # Actor position/rotation driven by these data aliases
       # TODO make these reference recorded_data: sections next
       #pos: sat_pos  # data alias associated with position
       #rot: sat_rot  # data alias associated with rotation
       time: time
       pos: sat_pos
       rot: sat_rot

 camera:
     follow: satellite
     near_clipping_plane_tolerance: 0.00001
