#!/usr/bin/env python3

import os

try:
    trick_build_dir = os.environ["TRICK_BUILD_DIR"]
except KeyError:
    trick_build_dir = ""

with open(trick_build_dir + 'build/CP_instances') as cp_instances:
    with open(trick_build_dir + 'build/top.i', 'w') as top:
        path = os.path.abspath(os.getcwd())
        instances = ''.join(cp_instances.readlines())
        top.write(
          '%module top\n'
          '\n'
          '%{\n'
          '#include "../S_source.hh"\n'
          '\n' +
          instances + '\n'
          '%}\n'
          '\n'
          '%import "' + trick_build_dir + 'build' + path + "/" + trick_build_dir + 'S_source_py.i"\n'
          '\n' +
          instances)
