#!/usr/bin/perl

use FindBin qw($RealBin);
use lib "$RealBin/pm" ;

use strict ;
use get_lib_deps ;

my $header ;
my @resolved_files ;

# Read in the Trick comment to be processed.
while ( <STDIN> ) {
    last if ( $_ =~ /END ICG PROCESSING/ ) ;
    $header .= $_ ;
}

(@resolved_files) = get_lib_deps($header, @ARGV[0]) ;

print map { "$_\n" } @resolved_files ;
