#!/usr/bin/perl

use FindBin qw($RealBin);
use lib "$RealBin/pm" ;

use swig_make ;

use strict ;

read_files_to_process() ;

write_makefile_swig_deps() ;

get_trick_headers() ;

# Remove SWIG: (NO) files, but not before they're written to the dependency file.
# If SWIG: (NO) is removed, Makefile_swig needs to be regenerated.
purge_swig_no_files() ;

write_makefile_swig() ;

write_lib_files() ;
