#!/usr/bin/perl

use FindBin qw($RealBin);
use lib "$RealBin/pm" ;

use File::Path qw(make_path);
use get_lib_deps ;

use strict ;

(my $ext_lib_files, my $files_to_process, my $md5s) = get_s_source_deps() ;
my @files_to_process = @$files_to_process ;
my @ext_lib_files = @$ext_lib_files ;
my %md5s = %$md5s ;

# Only want to run this with trickify-25. This check is to prevent this script from executing using the old trickify.mk method.
#TODO: Come up with a more elegant solution. Or drop this check when oldschool trickify.mk is no longer supported.
if($ENV{'AM_I_TRICKIFYING'}) {
    my %files_to_replace = trickify_map_fake_deps(\@files_to_process) ;
    foreach my $old_file (keys %files_to_replace) {
        foreach (@files_to_process) {
            $_ = $files_to_replace{$old_file} if $_ eq $old_file ; 
        }
    }
}

make_path("$ENV{TRICK_BUILD_DIR}build/trickify/swig/") unless -d "$ENV{TRICK_BUILD_DIR}build/trickify/swig/" ;

open FAKEDEPSMAP, ">$ENV{TRICK_BUILD_DIR}build/trickify/fake_deps_map" or die "Could not open $ENV{TRICK_BUILD_DIR}build/trickify/fake_deps_map" ;
print FAKEDEPSMAP map { "$_:$files_to_replace{$_}\n" } (sort keys %files_to_replace) ;
close FAKEDEPSMAP ;  

open FTP, ">$ENV{TRICK_BUILD_DIR}build/trickify/swig/files_to_process" or die "Could not open $ENV{TRICK_BUILD_DIR}build/trickify/swig/files_to_process" ;
print FTP map { "$_\n" } (@files_to_process) ;
close FTP ;  

open ELF, ">$ENV{TRICK_BUILD_DIR}build/trickify/swig/ext_lib_files" or die "Could not open $ENV{TRICK_BUILD_DIR}build/trickify/swig/ext_lib_files" ;
print ELF map { "$_\n" } (@ext_lib_files) ;
close ELF ;  

open MD5S, ">$ENV{TRICK_BUILD_DIR}build/trickify/swig/md5s" or die "Could not open $ENV{TRICK_BUILD_DIR}build/trickify/swig/md5s" ;
print MD5S map { "$_:$md5s{$_}\n" } (sort keys %md5s) ;
close MD5S ;  

