#!/usr/bin/perl

use FindBin qw($RealBin);
use lib "$RealBin/pm";

use File::Path qw(make_path);
use swig_make;

use strict;

read_files_to_process();

get_trick_headers();

purge_swig_no_files();

write_lib_files();
