#!/usr/bin/perl

use strict;
use warnings;

use FindBin qw($RealBin);
use lib "$RealBin/pm";

use swig_make qw(
    get_trick_headers
    purge_swig_no_files
    read_files_to_process
    replace_files_to_process
    trickify_map_fake_deps
    write_fake_deps_map
    write_lib_files
);

read_files_to_process();

# Only want to run this with trickify-25. This check is to prevent this script from executing using the old trickify.mk method.
#TODO: Come up with a more elegant solution. Or drop this check when oldschool trickify.mk is no longer supported.
if ( $ENV{'AM_I_TRICKIFYING'} ) {
    trickify_map_fake_deps();

    replace_files_to_process();
}

get_trick_headers();

purge_swig_no_files();

write_lib_files();

# Only want to run this with trickify-25. This check is to prevent this script from executing using the old trickify.mk method.
#TODO: Come up with a more elegant solution. Or drop this check when oldschool trickify.mk is no longer supported.
if ( $ENV{'AM_I_TRICKIFYING'} ) {
    write_fake_deps_map();
}
