
include ${TRICK_HOME}/share/trick/makefiles/Makefile.common
include ${TRICK_HOME}/share/trick/makefiles/Makefile.tricklib
-include Makefile_deps

#all: $(TRICK_LIB_DIR)/master.o
#
#trick: $(TRICK_LIB_DIR)/master.o
#
#$(OBJ_DIR)/master.o : master.cpp | $(OBJ_DIR)
#	$(TRICK_CPPC) $(TRICK_CXXFLAGS) -c $< -o $@
#
#$(TRICK_LIB_DIR)/master.o : $(OBJ_DIR)/master.o | $(TRICK_LIB_DIR)
#	$(CP) $< $@
#
#$(OBJ_DIR):
#	mkdir -p $(OBJ_DIR)
#
#clean: 
#	$(RM) -rf $(OBJ_DIR)
#
#real_clean: clean
#
#depend:
#	@ $(TRICK_CPPC) -MM $(TRICK_CXXFLAGS) master.cpp >> $(DEPTEMPFILE)
#	@ $(PERL) ${TRICK_HOME}/bin/depend_cp $(DEPTEMPFILE) > $(DEPFILE)
#	@ $(RM) $(DEPTEMPFILE)
#	@ echo "Created dependency file $(DEPFILE)"
#
#
#-include Makefile_deps

