# Phase 3 — install rules that assemble a working TRICK_HOME.
#
# The installed tree is the real product (D2/D3): sims are built by make against
# it, forever. Do NOT trust the top-level Makefile's `install` target as a spec —
# it is unmaintained and possibly broken. The authority is "what trick-CP needs to
# build and run a sim against the prefix" (Part E rule 4). The source tree is
# already TRICK_HOME-shaped (D3), so the install reproduces its bin/ include/
# libexec/ share/ layout plus the built archives and the *generated* config_user.mk
# and swig *.py wrappers — never the copies a prior make/configure left in-source.

# ── D6: library subdir (lib64 iff redhat-release && x86_64 && !32bit; else lib;
#         Darwin always lib) — mirror config_Linux.mk exactly, do NOT use
#         GNUInstallDirs (the perl flow hardcodes lib/lib64 discovery).
if(TRICK_FORCE_32BIT)
    set(TRICK_LIB_SUBDIR lib)
elseif(NOT APPLE AND EXISTS "/etc/redhat-release" AND CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
    set(TRICK_LIB_SUBDIR lib64)
else()
    set(TRICK_LIB_SUBDIR lib)
endif()
message(STATUS "Trick library subdir: ${TRICK_LIB_SUBDIR}")

# ── Static archives → ${TRICK_LIB_SUBDIR} (the A3 nine + var_binary_parser).
set(TRICK_INSTALL_ARCHIVES
    trick
    trick_mm
    trick_comm
    trick_connection_handlers
    trick_math
    trick_optimization
    trick_units
    trick_var_binary_parser
    trick_pyip
)
if(TRICK_USE_ER7_UTILS)
    list(APPEND TRICK_INSTALL_ARCHIVES er7_utils)
endif()
install(TARGETS ${TRICK_INSTALL_ARCHIVES}
    ARCHIVE DESTINATION ${TRICK_LIB_SUBDIR}
)

# ── bin/: the built trick-ICG, plus every checked-in perl driver. USE_SOURCE_
#          PERMISSIONS keeps the +x bit. trick-ICG is excluded from the source
#          copy because the build target supplies it (a stale in-source binary
#          may be present on a dev tree).
install(TARGETS trick-ICG RUNTIME DESTINATION bin)
install(DIRECTORY ${CMAKE_SOURCE_DIR}/bin/
    DESTINATION bin
    USE_SOURCE_PERMISSIONS
    PATTERN "trick-ICG" EXCLUDE
)

# ── include/: Trick headers (incl. compat) verbatim; er7_utils headers rehomed
#              from trick_source/er7_utils/**/*.hh to include/er7_utils/... .
install(DIRECTORY ${CMAKE_SOURCE_DIR}/include/trick DESTINATION include)
if(TRICK_USE_ER7_UTILS)
    install(DIRECTORY ${CMAKE_SOURCE_DIR}/trick_source/er7_utils/
        DESTINATION include/er7_utils
        FILES_MATCHING PATTERN "*.hh"
    )
endif()

# ── libexec/trick: perl helpers (configuration_processor, make_makefile_*, pm/,
#                   ...) verbatim. Java jars land here too but are a Phase 4 add.
install(DIRECTORY ${CMAKE_SOURCE_DIR}/libexec/trick
    DESTINATION libexec
    USE_SOURCE_PERMISSIONS
)

# ── share/trick: static content from source (makefiles, sim_objects, pymods,
#    trickops, swig *.i and the checked-in *.py, ...). Exclude the generated
#    artifacts so a dirty dev tree can't ship stale copies — the build-tree
#    versions are installed just below. config_user.mk is generated by
#    configure/CMake; the generated swig wrappers are sim_services/swig_*.py.
install(DIRECTORY ${CMAKE_SOURCE_DIR}/share/trick/
    DESTINATION share/trick
    USE_SOURCE_PERMISSIONS
    PATTERN "config_user.mk" EXCLUDE
    PATTERN "sim_services.py" EXCLUDE
    PATTERN "swig_double.py" EXCLUDE
    PATTERN "swig_int.py" EXCLUDE
    PATTERN "swig_ref.py" EXCLUDE
)
# Generated config_user.mk (D4 parity contract) and swig wrappers, from the build
# tree. The swig *.py are add_custom_command side effects (not a target output),
# so they are globbed at install time — they exist once the build has run.
install(FILES ${CMAKE_BINARY_DIR}/share/trick/makefiles/config_user.mk
    DESTINATION share/trick/makefiles
)
install(DIRECTORY ${CMAKE_BINARY_DIR}/share/trick/swig/
    DESTINATION share/trick/swig
    FILES_MATCHING PATTERN "*.py"
)

# ── share/man, share/doc: man pages and any prebuilt docs (best-effort).
install(DIRECTORY ${CMAKE_SOURCE_DIR}/share/man DESTINATION share)
if(EXISTS ${CMAKE_SOURCE_DIR}/share/doc)
    install(DIRECTORY ${CMAKE_SOURCE_DIR}/share/doc DESTINATION share)
endif()

# ── stage target: `cmake --build build --target stage` gives a runnable TRICK_HOME
#    at ${CMAKE_BINARY_DIR}/stage for sim-flow validation and CTest (D3). It depends
#    on the build targets so the install always reflects a fresh build.
set(TRICK_STAGE_DIR ${CMAKE_BINARY_DIR}/stage)
add_custom_target(stage
    COMMAND ${CMAKE_COMMAND} --install ${CMAKE_BINARY_DIR} --prefix ${TRICK_STAGE_DIR}
    COMMENT "Staging a runnable TRICK_HOME into ${TRICK_STAGE_DIR}"
    VERBATIM
)
add_dependencies(stage
    ${TRICK_INSTALL_ARCHIVES}
    trick-ICG
    trick_io_src_gen
)
