# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_m2ddd17f9284f93dc40b8a127bd142ae5')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_m2ddd17f9284f93dc40b8a127bd142ae5')
    _m2ddd17f9284f93dc40b8a127bd142ae5 = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_m2ddd17f9284f93dc40b8a127bd142ae5', [dirname(__file__)])
        except ImportError:
            import _m2ddd17f9284f93dc40b8a127bd142ae5
            return _m2ddd17f9284f93dc40b8a127bd142ae5
        try:
            _mod = imp.load_module('_m2ddd17f9284f93dc40b8a127bd142ae5', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _m2ddd17f9284f93dc40b8a127bd142ae5 = swig_import_helper()
    del swig_import_helper
else:
    import _m2ddd17f9284f93dc40b8a127bd142ae5
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _m2ddd17f9284f93dc40b8a127bd142ae5.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SwigPyIterator_equal(self, x)

    def copy(self):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SwigPyIterator_copy(self)

    def next(self):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SwigPyIterator_next(self)

    def __next__(self):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SwigPyIterator___next__(self)

    def previous(self):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SwigPyIterator_previous(self)

    def advance(self, n):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _m2ddd17f9284f93dc40b8a127bd142ae5.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)


def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    all_keys = [attr for attr in dir(class_type) if not attr.startswith('__')and attr != '_s' ]
    data_keys = sorted(class_type.__swig_setmethods__.keys())
    method_keys = [ x for x in all_keys if x not in data_keys ]
    raise AttributeError("Type %s does not contain member %s.\n%s data = %s\n%s methods = %s" %
     (self.__class__.__name__,name,self.__class__.__name__,data_keys,self.__class__.__name__,method_keys))

def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
# this line is changed to handle older swigs that used PySwigObject instead of the current SwigPyObject
        if type(value).__name__ == 'SwigPyObject' or type(value).__name__ == 'PySwigObject' :
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        all_keys = [attr for attr in dir(class_type) if not attr.startswith('__') and attr != '_s' ]
        data_keys = sorted(class_type.__swig_setmethods__.keys())
        method_keys = [ x for x in all_keys if x not in data_keys ]
        raise AttributeError("Type %s does not contain member %s.\n%s data = %s\n%s methods = %s" %
         (self.__class__.__name__,name,self.__class__.__name__,data_keys,self.__class__.__name__,method_keys))

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,1)

import sim_services
import me18dda184e7a3a5300b5efa2b558f756
class SimEnvironment(sim_services.Environment):
    __swig_setmethods__ = {}
    for _s in [sim_services.Environment]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SimEnvironment, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.Environment]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, SimEnvironment, name)
    __repr__ = _swig_repr

    def __init__(self, **kwargs):
        import _sim_services
        this = _m2ddd17f9284f93dc40b8a127bd142ae5.new_SimEnvironment()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "SimEnvironment", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def __getitem__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SimEnvironment___getitem__(self, *args)

    def __len__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SimEnvironment___len__(self, *args)
    __swig_destroy__ = _m2ddd17f9284f93dc40b8a127bd142ae5.delete_SimEnvironment
    __del__ = lambda self: None
SimEnvironment_swigregister = _m2ddd17f9284f93dc40b8a127bd142ae5.SimEnvironment_swigregister
SimEnvironment_swigregister(SimEnvironment)


def exec_collect_init(*args):
    return _m2ddd17f9284f93dc40b8a127bd142ae5.exec_collect_init(*args)
exec_collect_init = _m2ddd17f9284f93dc40b8a127bd142ae5.exec_collect_init
class SysSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SysSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, SysSimObject, name)
    __repr__ = _swig_repr
    __swig_getmethods__["sched"] = _m2ddd17f9284f93dc40b8a127bd142ae5.SysSimObject_sched_get
    if _newclass:
        sched = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.SysSimObject_sched_get)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m2ddd17f9284f93dc40b8a127bd142ae5.new_SysSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "SysSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SysSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SysSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SysSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SysSimObject___len__(self, *args)
    __swig_destroy__ = _m2ddd17f9284f93dc40b8a127bd142ae5.delete_SysSimObject
    __del__ = lambda self: None
SysSimObject_swigregister = _m2ddd17f9284f93dc40b8a127bd142ae5.SysSimObject_swigregister
SysSimObject_swigregister(SysSimObject)

class MemoryManagerSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, MemoryManagerSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, MemoryManagerSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["mm"] = _m2ddd17f9284f93dc40b8a127bd142ae5.MemoryManagerSimObject_mm_set
    __swig_getmethods__["mm"] = _m2ddd17f9284f93dc40b8a127bd142ae5.MemoryManagerSimObject_mm_get
    if _newclass:
        mm = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.MemoryManagerSimObject_mm_get, _m2ddd17f9284f93dc40b8a127bd142ae5.MemoryManagerSimObject_mm_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m2ddd17f9284f93dc40b8a127bd142ae5.new_MemoryManagerSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "MemoryManagerSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.MemoryManagerSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.MemoryManagerSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.MemoryManagerSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.MemoryManagerSimObject___len__(self, *args)
    __swig_destroy__ = _m2ddd17f9284f93dc40b8a127bd142ae5.delete_MemoryManagerSimObject
    __del__ = lambda self: None
MemoryManagerSimObject_swigregister = _m2ddd17f9284f93dc40b8a127bd142ae5.MemoryManagerSimObject_swigregister
MemoryManagerSimObject_swigregister(MemoryManagerSimObject)

class CheckPointRestartSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, CheckPointRestartSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, CheckPointRestartSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cpr"] = _m2ddd17f9284f93dc40b8a127bd142ae5.CheckPointRestartSimObject_cpr_set
    __swig_getmethods__["cpr"] = _m2ddd17f9284f93dc40b8a127bd142ae5.CheckPointRestartSimObject_cpr_get
    if _newclass:
        cpr = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.CheckPointRestartSimObject_cpr_get, _m2ddd17f9284f93dc40b8a127bd142ae5.CheckPointRestartSimObject_cpr_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m2ddd17f9284f93dc40b8a127bd142ae5.new_CheckPointRestartSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "CheckPointRestartSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.CheckPointRestartSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.CheckPointRestartSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.CheckPointRestartSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.CheckPointRestartSimObject___len__(self, *args)
    __swig_destroy__ = _m2ddd17f9284f93dc40b8a127bd142ae5.delete_CheckPointRestartSimObject
    __del__ = lambda self: None
CheckPointRestartSimObject_swigregister = _m2ddd17f9284f93dc40b8a127bd142ae5.CheckPointRestartSimObject_swigregister
CheckPointRestartSimObject_swigregister(CheckPointRestartSimObject)

class SieSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SieSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, SieSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["sie"] = _m2ddd17f9284f93dc40b8a127bd142ae5.SieSimObject_sie_set
    __swig_getmethods__["sie"] = _m2ddd17f9284f93dc40b8a127bd142ae5.SieSimObject_sie_get
    if _newclass:
        sie = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.SieSimObject_sie_get, _m2ddd17f9284f93dc40b8a127bd142ae5.SieSimObject_sie_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m2ddd17f9284f93dc40b8a127bd142ae5.new_SieSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "SieSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SieSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SieSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SieSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.SieSimObject___len__(self, *args)
    __swig_destroy__ = _m2ddd17f9284f93dc40b8a127bd142ae5.delete_SieSimObject
    __del__ = lambda self: None
SieSimObject_swigregister = _m2ddd17f9284f93dc40b8a127bd142ae5.SieSimObject_swigregister
SieSimObject_swigregister(SieSimObject)

class CommandLineArgumentsSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, CommandLineArgumentsSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, CommandLineArgumentsSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cmd_args"] = _m2ddd17f9284f93dc40b8a127bd142ae5.CommandLineArgumentsSimObject_cmd_args_set
    __swig_getmethods__["cmd_args"] = _m2ddd17f9284f93dc40b8a127bd142ae5.CommandLineArgumentsSimObject_cmd_args_get
    if _newclass:
        cmd_args = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.CommandLineArgumentsSimObject_cmd_args_get, _m2ddd17f9284f93dc40b8a127bd142ae5.CommandLineArgumentsSimObject_cmd_args_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m2ddd17f9284f93dc40b8a127bd142ae5.new_CommandLineArgumentsSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "CommandLineArgumentsSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.CommandLineArgumentsSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.CommandLineArgumentsSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.CommandLineArgumentsSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.CommandLineArgumentsSimObject___len__(self, *args)
    __swig_destroy__ = _m2ddd17f9284f93dc40b8a127bd142ae5.delete_CommandLineArgumentsSimObject
    __del__ = lambda self: None
CommandLineArgumentsSimObject_swigregister = _m2ddd17f9284f93dc40b8a127bd142ae5.CommandLineArgumentsSimObject_swigregister
CommandLineArgumentsSimObject_swigregister(CommandLineArgumentsSimObject)

class MessageSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, MessageSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, MessageSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["mpublisher"] = _m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_mpublisher_set
    __swig_getmethods__["mpublisher"] = _m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_mpublisher_get
    if _newclass:
        mpublisher = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_mpublisher_get, _m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_mpublisher_set)
    __swig_setmethods__["mcout"] = _m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_mcout_set
    __swig_getmethods__["mcout"] = _m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_mcout_get
    if _newclass:
        mcout = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_mcout_get, _m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_mcout_set)
    __swig_setmethods__["mtcout"] = _m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_mtcout_set
    __swig_getmethods__["mtcout"] = _m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_mtcout_get
    if _newclass:
        mtcout = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_mtcout_get, _m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_mtcout_set)
    __swig_getmethods__["mfile"] = _m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_mfile_get
    if _newclass:
        mfile = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_mfile_get)
    __swig_setmethods__["mdevice"] = _m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_mdevice_set
    __swig_getmethods__["mdevice"] = _m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_mdevice_get
    if _newclass:
        mdevice = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_mdevice_get, _m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_mdevice_set)
    __swig_getmethods__["pfile"] = _m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_pfile_get
    if _newclass:
        pfile = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_pfile_get)
    __swig_setmethods__["message_file_manager"] = _m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_message_file_manager_set
    __swig_getmethods__["message_file_manager"] = _m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_message_file_manager_get
    if _newclass:
        message_file_manager = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_message_file_manager_get, _m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_message_file_manager_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m2ddd17f9284f93dc40b8a127bd142ae5.new_MessageSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "MessageSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_call_function_double(self, *args)

    def separate_thread_set_enabled(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_separate_thread_set_enabled(self, *args)

    def __getitem__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject___len__(self, *args)
    __swig_destroy__ = _m2ddd17f9284f93dc40b8a127bd142ae5.delete_MessageSimObject
    __del__ = lambda self: None
MessageSimObject_swigregister = _m2ddd17f9284f93dc40b8a127bd142ae5.MessageSimObject_swigregister
MessageSimObject_swigregister(MessageSimObject)

class JITSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, JITSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, JITSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["jit"] = _m2ddd17f9284f93dc40b8a127bd142ae5.JITSimObject_jit_set
    __swig_getmethods__["jit"] = _m2ddd17f9284f93dc40b8a127bd142ae5.JITSimObject_jit_get
    if _newclass:
        jit = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.JITSimObject_jit_get, _m2ddd17f9284f93dc40b8a127bd142ae5.JITSimObject_jit_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m2ddd17f9284f93dc40b8a127bd142ae5.new_JITSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "JITSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.JITSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.JITSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.JITSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.JITSimObject___len__(self, *args)
    __swig_destroy__ = _m2ddd17f9284f93dc40b8a127bd142ae5.delete_JITSimObject
    __del__ = lambda self: None
JITSimObject_swigregister = _m2ddd17f9284f93dc40b8a127bd142ae5.JITSimObject_swigregister
JITSimObject_swigregister(JITSimObject)

class InputProcessorSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, InputProcessorSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, InputProcessorSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["ip"] = _m2ddd17f9284f93dc40b8a127bd142ae5.InputProcessorSimObject_ip_set
    __swig_getmethods__["ip"] = _m2ddd17f9284f93dc40b8a127bd142ae5.InputProcessorSimObject_ip_get
    if _newclass:
        ip = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.InputProcessorSimObject_ip_get, _m2ddd17f9284f93dc40b8a127bd142ae5.InputProcessorSimObject_ip_set)
    __swig_setmethods__["mtv"] = _m2ddd17f9284f93dc40b8a127bd142ae5.InputProcessorSimObject_mtv_set
    __swig_getmethods__["mtv"] = _m2ddd17f9284f93dc40b8a127bd142ae5.InputProcessorSimObject_mtv_get
    if _newclass:
        mtv = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.InputProcessorSimObject_mtv_get, _m2ddd17f9284f93dc40b8a127bd142ae5.InputProcessorSimObject_mtv_set)
    __swig_setmethods__["units_map_ptr"] = _m2ddd17f9284f93dc40b8a127bd142ae5.InputProcessorSimObject_units_map_ptr_set
    __swig_getmethods__["units_map_ptr"] = _m2ddd17f9284f93dc40b8a127bd142ae5.InputProcessorSimObject_units_map_ptr_get
    if _newclass:
        units_map_ptr = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.InputProcessorSimObject_units_map_ptr_get, _m2ddd17f9284f93dc40b8a127bd142ae5.InputProcessorSimObject_units_map_ptr_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m2ddd17f9284f93dc40b8a127bd142ae5.new_InputProcessorSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "InputProcessorSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW


    __swig_destroy__ = _m2ddd17f9284f93dc40b8a127bd142ae5.delete_InputProcessorSimObject
    __del__ = lambda self: None

    def call_function(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.InputProcessorSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.InputProcessorSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.InputProcessorSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.InputProcessorSimObject___len__(self, *args)
InputProcessorSimObject_swigregister = _m2ddd17f9284f93dc40b8a127bd142ae5.InputProcessorSimObject_swigregister
InputProcessorSimObject_swigregister(InputProcessorSimObject)

class ThreadProcessEventSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ThreadProcessEventSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, ThreadProcessEventSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["ep"] = _m2ddd17f9284f93dc40b8a127bd142ae5.ThreadProcessEventSimObject_ep_set
    __swig_getmethods__["ep"] = _m2ddd17f9284f93dc40b8a127bd142ae5.ThreadProcessEventSimObject_ep_get
    if _newclass:
        ep = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.ThreadProcessEventSimObject_ep_get, _m2ddd17f9284f93dc40b8a127bd142ae5.ThreadProcessEventSimObject_ep_set)

    def __init__(self, *args, **kwargs):
        import _sim_services
        this = _m2ddd17f9284f93dc40b8a127bd142ae5.new_ThreadProcessEventSimObject(*args)
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            this.own(0)
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "ThreadProcessEventSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.ThreadProcessEventSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.ThreadProcessEventSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.ThreadProcessEventSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.ThreadProcessEventSimObject___len__(self, *args)
    __swig_destroy__ = _m2ddd17f9284f93dc40b8a127bd142ae5.delete_ThreadProcessEventSimObject
    __del__ = lambda self: None
ThreadProcessEventSimObject_swigregister = _m2ddd17f9284f93dc40b8a127bd142ae5.ThreadProcessEventSimObject_swigregister
ThreadProcessEventSimObject_swigregister(ThreadProcessEventSimObject)

class EventManagerSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, EventManagerSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, EventManagerSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["em"] = _m2ddd17f9284f93dc40b8a127bd142ae5.EventManagerSimObject_em_set
    __swig_getmethods__["em"] = _m2ddd17f9284f93dc40b8a127bd142ae5.EventManagerSimObject_em_get
    if _newclass:
        em = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.EventManagerSimObject_em_get, _m2ddd17f9284f93dc40b8a127bd142ae5.EventManagerSimObject_em_set)
    __swig_setmethods__["ep"] = _m2ddd17f9284f93dc40b8a127bd142ae5.EventManagerSimObject_ep_set
    __swig_getmethods__["ep"] = _m2ddd17f9284f93dc40b8a127bd142ae5.EventManagerSimObject_ep_get
    if _newclass:
        ep = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.EventManagerSimObject_ep_get, _m2ddd17f9284f93dc40b8a127bd142ae5.EventManagerSimObject_ep_set)
    __swig_setmethods__["thread_process_event_so"] = _m2ddd17f9284f93dc40b8a127bd142ae5.EventManagerSimObject_thread_process_event_so_set
    __swig_getmethods__["thread_process_event_so"] = _m2ddd17f9284f93dc40b8a127bd142ae5.EventManagerSimObject_thread_process_event_so_get
    if _newclass:
        thread_process_event_so = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.EventManagerSimObject_thread_process_event_so_get, _m2ddd17f9284f93dc40b8a127bd142ae5.EventManagerSimObject_thread_process_event_so_set)
    __swig_setmethods__["thread_process_event_so_names"] = _m2ddd17f9284f93dc40b8a127bd142ae5.EventManagerSimObject_thread_process_event_so_names_set
    __swig_getmethods__["thread_process_event_so_names"] = _m2ddd17f9284f93dc40b8a127bd142ae5.EventManagerSimObject_thread_process_event_so_names_get
    if _newclass:
        thread_process_event_so_names = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.EventManagerSimObject_thread_process_event_so_names_get, _m2ddd17f9284f93dc40b8a127bd142ae5.EventManagerSimObject_thread_process_event_so_names_set)

    def create_thread_process_event(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.EventManagerSimObject_create_thread_process_event(self, *args)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m2ddd17f9284f93dc40b8a127bd142ae5.new_EventManagerSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "EventManagerSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW


    __swig_destroy__ = _m2ddd17f9284f93dc40b8a127bd142ae5.delete_EventManagerSimObject
    __del__ = lambda self: None

    def call_function(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.EventManagerSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.EventManagerSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.EventManagerSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.EventManagerSimObject___len__(self, *args)
EventManagerSimObject_swigregister = _m2ddd17f9284f93dc40b8a127bd142ae5.EventManagerSimObject_swigregister
EventManagerSimObject_swigregister(EventManagerSimObject)

class VariableServerSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, VariableServerSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, VariableServerSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["vs"] = _m2ddd17f9284f93dc40b8a127bd142ae5.VariableServerSimObject_vs_set
    __swig_getmethods__["vs"] = _m2ddd17f9284f93dc40b8a127bd142ae5.VariableServerSimObject_vs_get
    if _newclass:
        vs = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.VariableServerSimObject_vs_get, _m2ddd17f9284f93dc40b8a127bd142ae5.VariableServerSimObject_vs_set)
    __swig_getmethods__["sim_control_panel"] = _m2ddd17f9284f93dc40b8a127bd142ae5.VariableServerSimObject_sim_control_panel_get
    if _newclass:
        sim_control_panel = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.VariableServerSimObject_sim_control_panel_get)
    __swig_getmethods__["trick_view"] = _m2ddd17f9284f93dc40b8a127bd142ae5.VariableServerSimObject_trick_view_get
    if _newclass:
        trick_view = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.VariableServerSimObject_trick_view_get)
    __swig_getmethods__["malfunctions_trick_view"] = _m2ddd17f9284f93dc40b8a127bd142ae5.VariableServerSimObject_malfunctions_trick_view_get
    if _newclass:
        malfunctions_trick_view = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.VariableServerSimObject_malfunctions_trick_view_get)
    __swig_getmethods__["stripchart"] = _m2ddd17f9284f93dc40b8a127bd142ae5.VariableServerSimObject_stripchart_get
    if _newclass:
        stripchart = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.VariableServerSimObject_stripchart_get)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m2ddd17f9284f93dc40b8a127bd142ae5.new_VariableServerSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "VariableServerSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.VariableServerSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.VariableServerSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.VariableServerSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.VariableServerSimObject___len__(self, *args)
    __swig_destroy__ = _m2ddd17f9284f93dc40b8a127bd142ae5.delete_VariableServerSimObject
    __del__ = lambda self: None
VariableServerSimObject_swigregister = _m2ddd17f9284f93dc40b8a127bd142ae5.VariableServerSimObject_swigregister
VariableServerSimObject_swigregister(VariableServerSimObject)

class DataRecordDispatcherSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, DataRecordDispatcherSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, DataRecordDispatcherSimObject, name)
    __repr__ = _swig_repr
    __swig_getmethods__["drd"] = _m2ddd17f9284f93dc40b8a127bd142ae5.DataRecordDispatcherSimObject_drd_get
    if _newclass:
        drd = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.DataRecordDispatcherSimObject_drd_get)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m2ddd17f9284f93dc40b8a127bd142ae5.new_DataRecordDispatcherSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "DataRecordDispatcherSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.DataRecordDispatcherSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.DataRecordDispatcherSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.DataRecordDispatcherSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.DataRecordDispatcherSimObject___len__(self, *args)
    __swig_destroy__ = _m2ddd17f9284f93dc40b8a127bd142ae5.delete_DataRecordDispatcherSimObject
    __del__ = lambda self: None
DataRecordDispatcherSimObject_swigregister = _m2ddd17f9284f93dc40b8a127bd142ae5.DataRecordDispatcherSimObject_swigregister
DataRecordDispatcherSimObject_swigregister(DataRecordDispatcherSimObject)

class RTSyncSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, RTSyncSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, RTSyncSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["gtod_clock"] = _m2ddd17f9284f93dc40b8a127bd142ae5.RTSyncSimObject_gtod_clock_set
    __swig_getmethods__["gtod_clock"] = _m2ddd17f9284f93dc40b8a127bd142ae5.RTSyncSimObject_gtod_clock_get
    if _newclass:
        gtod_clock = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.RTSyncSimObject_gtod_clock_get, _m2ddd17f9284f93dc40b8a127bd142ae5.RTSyncSimObject_gtod_clock_set)
    __swig_setmethods__["itimer"] = _m2ddd17f9284f93dc40b8a127bd142ae5.RTSyncSimObject_itimer_set
    __swig_getmethods__["itimer"] = _m2ddd17f9284f93dc40b8a127bd142ae5.RTSyncSimObject_itimer_get
    if _newclass:
        itimer = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.RTSyncSimObject_itimer_get, _m2ddd17f9284f93dc40b8a127bd142ae5.RTSyncSimObject_itimer_set)
    __swig_setmethods__["rt_sync"] = _m2ddd17f9284f93dc40b8a127bd142ae5.RTSyncSimObject_rt_sync_set
    __swig_getmethods__["rt_sync"] = _m2ddd17f9284f93dc40b8a127bd142ae5.RTSyncSimObject_rt_sync_get
    if _newclass:
        rt_sync = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.RTSyncSimObject_rt_sync_get, _m2ddd17f9284f93dc40b8a127bd142ae5.RTSyncSimObject_rt_sync_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m2ddd17f9284f93dc40b8a127bd142ae5.new_RTSyncSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "RTSyncSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.RTSyncSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.RTSyncSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.RTSyncSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.RTSyncSimObject___len__(self, *args)
    __swig_destroy__ = _m2ddd17f9284f93dc40b8a127bd142ae5.delete_RTSyncSimObject
    __del__ = lambda self: None
RTSyncSimObject_swigregister = _m2ddd17f9284f93dc40b8a127bd142ae5.RTSyncSimObject_swigregister
RTSyncSimObject_swigregister(RTSyncSimObject)

class FrameLogSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, FrameLogSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, FrameLogSimObject, name)
    __repr__ = _swig_repr
    __swig_getmethods__["frame_log"] = _m2ddd17f9284f93dc40b8a127bd142ae5.FrameLogSimObject_frame_log_get
    if _newclass:
        frame_log = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.FrameLogSimObject_frame_log_get)

    def __init__(self, *args, **kwargs):
        import _sim_services
        this = _m2ddd17f9284f93dc40b8a127bd142ae5.new_FrameLogSimObject(*args)
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            this.own(0)
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "FrameLogSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.FrameLogSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.FrameLogSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.FrameLogSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.FrameLogSimObject___len__(self, *args)
    __swig_destroy__ = _m2ddd17f9284f93dc40b8a127bd142ae5.delete_FrameLogSimObject
    __del__ = lambda self: None
FrameLogSimObject_swigregister = _m2ddd17f9284f93dc40b8a127bd142ae5.FrameLogSimObject_swigregister
FrameLogSimObject_swigregister(FrameLogSimObject)

class UnitTestSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, UnitTestSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, UnitTestSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["unit_tests"] = _m2ddd17f9284f93dc40b8a127bd142ae5.UnitTestSimObject_unit_tests_set
    __swig_getmethods__["unit_tests"] = _m2ddd17f9284f93dc40b8a127bd142ae5.UnitTestSimObject_unit_tests_get
    if _newclass:
        unit_tests = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.UnitTestSimObject_unit_tests_get, _m2ddd17f9284f93dc40b8a127bd142ae5.UnitTestSimObject_unit_tests_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m2ddd17f9284f93dc40b8a127bd142ae5.new_UnitTestSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "UnitTestSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.UnitTestSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.UnitTestSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.UnitTestSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.UnitTestSimObject___len__(self, *args)
    __swig_destroy__ = _m2ddd17f9284f93dc40b8a127bd142ae5.delete_UnitTestSimObject
    __del__ = lambda self: None
UnitTestSimObject_swigregister = _m2ddd17f9284f93dc40b8a127bd142ae5.UnitTestSimObject_swigregister
UnitTestSimObject_swigregister(UnitTestSimObject)

class UdUnitsSimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, UdUnitsSimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, UdUnitsSimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["udunits"] = _m2ddd17f9284f93dc40b8a127bd142ae5.UdUnitsSimObject_udunits_set
    __swig_getmethods__["udunits"] = _m2ddd17f9284f93dc40b8a127bd142ae5.UdUnitsSimObject_udunits_get
    if _newclass:
        udunits = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.UdUnitsSimObject_udunits_get, _m2ddd17f9284f93dc40b8a127bd142ae5.UdUnitsSimObject_udunits_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m2ddd17f9284f93dc40b8a127bd142ae5.new_UdUnitsSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "UdUnitsSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.UdUnitsSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.UdUnitsSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.UdUnitsSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.UdUnitsSimObject___len__(self, *args)
    __swig_destroy__ = _m2ddd17f9284f93dc40b8a127bd142ae5.delete_UdUnitsSimObject
    __del__ = lambda self: None
UdUnitsSimObject_swigregister = _m2ddd17f9284f93dc40b8a127bd142ae5.UdUnitsSimObject_swigregister
UdUnitsSimObject_swigregister(UdUnitsSimObject)

class BodySimObject(sim_services.SimObject):
    __swig_setmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, BodySimObject, name, value)
    __swig_getmethods__ = {}
    for _s in [sim_services.SimObject]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, BodySimObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["body"] = _m2ddd17f9284f93dc40b8a127bd142ae5.BodySimObject_body_set
    __swig_getmethods__["body"] = _m2ddd17f9284f93dc40b8a127bd142ae5.BodySimObject_body_get
    if _newclass:
        body = _swig_property(_m2ddd17f9284f93dc40b8a127bd142ae5.BodySimObject_body_get, _m2ddd17f9284f93dc40b8a127bd142ae5.BodySimObject_body_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _m2ddd17f9284f93dc40b8a127bd142ae5.new_BodySimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "BodySimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.BodySimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.BodySimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.BodySimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _m2ddd17f9284f93dc40b8a127bd142ae5.BodySimObject___len__(self, *args)
    __swig_destroy__ = _m2ddd17f9284f93dc40b8a127bd142ae5.delete_BodySimObject
    __del__ = lambda self: None
BodySimObject_swigregister = _m2ddd17f9284f93dc40b8a127bd142ae5.BodySimObject_swigregister
BodySimObject_swigregister(BodySimObject)


def castAsSimEnvironment(*args):
    return _m2ddd17f9284f93dc40b8a127bd142ae5.castAsSimEnvironment(*args)
castAsSimEnvironment = _m2ddd17f9284f93dc40b8a127bd142ae5.castAsSimEnvironment

def castAsSysSimObject(*args):
    return _m2ddd17f9284f93dc40b8a127bd142ae5.castAsSysSimObject(*args)
castAsSysSimObject = _m2ddd17f9284f93dc40b8a127bd142ae5.castAsSysSimObject

def castAsMemoryManagerSimObject(*args):
    return _m2ddd17f9284f93dc40b8a127bd142ae5.castAsMemoryManagerSimObject(*args)
castAsMemoryManagerSimObject = _m2ddd17f9284f93dc40b8a127bd142ae5.castAsMemoryManagerSimObject

def castAsCheckPointRestartSimObject(*args):
    return _m2ddd17f9284f93dc40b8a127bd142ae5.castAsCheckPointRestartSimObject(*args)
castAsCheckPointRestartSimObject = _m2ddd17f9284f93dc40b8a127bd142ae5.castAsCheckPointRestartSimObject

def castAsSieSimObject(*args):
    return _m2ddd17f9284f93dc40b8a127bd142ae5.castAsSieSimObject(*args)
castAsSieSimObject = _m2ddd17f9284f93dc40b8a127bd142ae5.castAsSieSimObject

def castAsCommandLineArgumentsSimObject(*args):
    return _m2ddd17f9284f93dc40b8a127bd142ae5.castAsCommandLineArgumentsSimObject(*args)
castAsCommandLineArgumentsSimObject = _m2ddd17f9284f93dc40b8a127bd142ae5.castAsCommandLineArgumentsSimObject

def castAsMessageSimObject(*args):
    return _m2ddd17f9284f93dc40b8a127bd142ae5.castAsMessageSimObject(*args)
castAsMessageSimObject = _m2ddd17f9284f93dc40b8a127bd142ae5.castAsMessageSimObject

def castAsJITSimObject(*args):
    return _m2ddd17f9284f93dc40b8a127bd142ae5.castAsJITSimObject(*args)
castAsJITSimObject = _m2ddd17f9284f93dc40b8a127bd142ae5.castAsJITSimObject

def castAsInputProcessorSimObject(*args):
    return _m2ddd17f9284f93dc40b8a127bd142ae5.castAsInputProcessorSimObject(*args)
castAsInputProcessorSimObject = _m2ddd17f9284f93dc40b8a127bd142ae5.castAsInputProcessorSimObject

def castAsThreadProcessEventSimObject(*args):
    return _m2ddd17f9284f93dc40b8a127bd142ae5.castAsThreadProcessEventSimObject(*args)
castAsThreadProcessEventSimObject = _m2ddd17f9284f93dc40b8a127bd142ae5.castAsThreadProcessEventSimObject

def castAsEventManagerSimObject(*args):
    return _m2ddd17f9284f93dc40b8a127bd142ae5.castAsEventManagerSimObject(*args)
castAsEventManagerSimObject = _m2ddd17f9284f93dc40b8a127bd142ae5.castAsEventManagerSimObject

def castAsVariableServerSimObject(*args):
    return _m2ddd17f9284f93dc40b8a127bd142ae5.castAsVariableServerSimObject(*args)
castAsVariableServerSimObject = _m2ddd17f9284f93dc40b8a127bd142ae5.castAsVariableServerSimObject

def castAsDataRecordDispatcherSimObject(*args):
    return _m2ddd17f9284f93dc40b8a127bd142ae5.castAsDataRecordDispatcherSimObject(*args)
castAsDataRecordDispatcherSimObject = _m2ddd17f9284f93dc40b8a127bd142ae5.castAsDataRecordDispatcherSimObject

def castAsRTSyncSimObject(*args):
    return _m2ddd17f9284f93dc40b8a127bd142ae5.castAsRTSyncSimObject(*args)
castAsRTSyncSimObject = _m2ddd17f9284f93dc40b8a127bd142ae5.castAsRTSyncSimObject

def castAsFrameLogSimObject(*args):
    return _m2ddd17f9284f93dc40b8a127bd142ae5.castAsFrameLogSimObject(*args)
castAsFrameLogSimObject = _m2ddd17f9284f93dc40b8a127bd142ae5.castAsFrameLogSimObject

def castAsUnitTestSimObject(*args):
    return _m2ddd17f9284f93dc40b8a127bd142ae5.castAsUnitTestSimObject(*args)
castAsUnitTestSimObject = _m2ddd17f9284f93dc40b8a127bd142ae5.castAsUnitTestSimObject

def castAsUdUnitsSimObject(*args):
    return _m2ddd17f9284f93dc40b8a127bd142ae5.castAsUdUnitsSimObject(*args)
castAsUdUnitsSimObject = _m2ddd17f9284f93dc40b8a127bd142ae5.castAsUdUnitsSimObject

def castAsBodySimObject(*args):
    return _m2ddd17f9284f93dc40b8a127bd142ae5.castAsBodySimObject(*args)
castAsBodySimObject = _m2ddd17f9284f93dc40b8a127bd142ae5.castAsBodySimObject
# This file is compatible with both classic and new-style classes.


