# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_swig_int')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_swig_int')
    _swig_int = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_swig_int', [dirname(__file__)])
        except ImportError:
            import _swig_int
            return _swig_int
        try:
            _mod = imp.load_module('_swig_int', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _swig_int = swig_import_helper()
    del swig_import_helper
else:
    import _swig_int
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class swig_int(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, swig_int, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, swig_int, name)
    __swig_setmethods__["units"] = _swig_int.swig_int_units_set
    __swig_getmethods__["units"] = _swig_int.swig_int_units_get
    if _newclass:
        units = _swig_property(_swig_int.swig_int_units_get, _swig_int.swig_int_units_set)

    def __str__(self):
        return _swig_int.swig_int___str__(self)

    def __repr__(self):
        return _swig_int.swig_int___repr__(self)

    def __add__(self, obj1):
        return _swig_int.swig_int___add__(self, obj1)

    def __sub__(self, obj1):
        return _swig_int.swig_int___sub__(self, obj1)

    def __mul__(self, obj1):
        return _swig_int.swig_int___mul__(self, obj1)

    def __div__(self, obj1):
        return _swig_int.swig_int___div__(self, obj1)

    def __truediv__(self, obj1):
        return _swig_int.swig_int___truediv__(self, obj1)

    def __floordiv__(self, obj1):
        return _swig_int.swig_int___floordiv__(self, obj1)

    def __mod__(self, obj1):
        return _swig_int.swig_int___mod__(self, obj1)

    def __pow__(self, obj1):
        return _swig_int.swig_int___pow__(self, obj1)

    def __lshift__(self, obj1):
        return _swig_int.swig_int___lshift__(self, obj1)

    def __rshift__(self, obj1):
        return _swig_int.swig_int___rshift__(self, obj1)

    def __and__(self, obj1):
        return _swig_int.swig_int___and__(self, obj1)

    def __xor__(self, obj1):
        return _swig_int.swig_int___xor__(self, obj1)

    def __or__(self, obj1):
        return _swig_int.swig_int___or__(self, obj1)

    def __radd__(self, obj1):
        return _swig_int.swig_int___radd__(self, obj1)

    def __rsub__(self, obj1):
        return _swig_int.swig_int___rsub__(self, obj1)

    def __rmul__(self, obj1):
        return _swig_int.swig_int___rmul__(self, obj1)

    def __rdiv__(self, obj1):
        return _swig_int.swig_int___rdiv__(self, obj1)

    def __rtruediv__(self, obj1):
        return _swig_int.swig_int___rtruediv__(self, obj1)

    def __rfloordiv__(self, obj1):
        return _swig_int.swig_int___rfloordiv__(self, obj1)

    def __rmod__(self, obj1):
        return _swig_int.swig_int___rmod__(self, obj1)

    def __rpow__(self, obj1):
        return _swig_int.swig_int___rpow__(self, obj1)

    def __rlshift__(self, obj1):
        return _swig_int.swig_int___rlshift__(self, obj1)

    def __rrshift__(self, obj1):
        return _swig_int.swig_int___rrshift__(self, obj1)

    def __rand__(self, obj1):
        return _swig_int.swig_int___rand__(self, obj1)

    def __rxor__(self, obj1):
        return _swig_int.swig_int___rxor__(self, obj1)

    def __ror__(self, obj1):
        return _swig_int.swig_int___ror__(self, obj1)

    def __iadd__(self, obj1):
        return _swig_int.swig_int___iadd__(self, obj1)

    def __isub__(self, obj1):
        return _swig_int.swig_int___isub__(self, obj1)

    def __imul__(self, obj1):
        return _swig_int.swig_int___imul__(self, obj1)

    def __idiv__(self, obj1):
        return _swig_int.swig_int___idiv__(self, obj1)

    def __itruediv__(self, obj1):
        return _swig_int.swig_int___itruediv__(self, obj1)

    def __ifloordiv__(self, obj1):
        return _swig_int.swig_int___ifloordiv__(self, obj1)

    def __imod__(self, obj1):
        return _swig_int.swig_int___imod__(self, obj1)

    def __ipow__(self, obj1):
        return _swig_int.swig_int___ipow__(self, obj1)

    def __ilshift__(self, obj1):
        return _swig_int.swig_int___ilshift__(self, obj1)

    def __irshift__(self, obj1):
        return _swig_int.swig_int___irshift__(self, obj1)

    def __iand__(self, obj1):
        return _swig_int.swig_int___iand__(self, obj1)

    def __ixor__(self, obj1):
        return _swig_int.swig_int___ixor__(self, obj1)

    def __ior__(self, obj1):
        return _swig_int.swig_int___ior__(self, obj1)

    def __lt__(self, obj1):
        return _swig_int.swig_int___lt__(self, obj1)

    def __le__(self, obj1):
        return _swig_int.swig_int___le__(self, obj1)

    def __eq__(self, obj1):
        return _swig_int.swig_int___eq__(self, obj1)

    def __ne__(self, obj1):
        return _swig_int.swig_int___ne__(self, obj1)

    def __gt__(self, obj1):
        return _swig_int.swig_int___gt__(self, obj1)

    def __ge__(self, obj1):
        return _swig_int.swig_int___ge__(self, obj1)

    def __neg__(self):
        return _swig_int.swig_int___neg__(self)

    def __pos__(self):
        return _swig_int.swig_int___pos__(self)

    def __abs__(self):
        return _swig_int.swig_int___abs__(self)

    def __invert__(self):
        return _swig_int.swig_int___invert__(self)

    def __nonzero__(self):
        return _swig_int.swig_int___nonzero__(self)

    def __int__(self):
        return _swig_int.swig_int___int__(self)

    def __long__(self):
        return _swig_int.swig_int___long__(self)

    def __float__(self):
        return _swig_int.swig_int___float__(self)

    def __oct__(self):
        return _swig_int.swig_int___oct__(self)

    def __hex__(self):
        return _swig_int.swig_int___hex__(self)

    def __len__(self):
        return _swig_int.swig_int___len__(self)

    def __index__(self):
        return _swig_int.swig_int___index__(self)

    def __bool__(self):
        return _swig_int.swig_int___bool__(self)

    def __init__(self):
        this = _swig_int.new_swig_int()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _swig_int.delete_swig_int
    __del__ = lambda self: None
swig_int_swigregister = _swig_int.swig_int_swigregister
swig_int_swigregister(swig_int)

# This file is compatible with both classic and new-style classes.


