name: "Report Linux"
on:
  workflow_run:
    workflows: ["Linux"] # runs after CI workflow
    types:
      - completed
jobs:
  report:
    strategy:
      fail-fast: false
      matrix:
        cfg:
          #-------- Operating Systems ----------------
          - { os: ubuntu, tag: 24.04, arch: debian, arch_ver: 12 }
          - { os: oraclelinux, tag: 8, arch: rhel, arch_ver: 8 }
          - { os: rockylinux, tag: 8, arch: rhel, arch_ver: 8 }
          - { os: rockylinux, tag: 9, arch: rhel, arch_ver: 9 }
          - { os: rockylinux, tag: 10, arch: rhel, arch_ver: 10 }

    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v2
        with:
          artifact: Trick_${{matrix.cfg.os}}${{matrix.cfg.tag}} # artifact name
          name: Results_Trick_${{matrix.cfg.os}}${{matrix.cfg.tag}} # Name of the check run which will be created
          path: "*.xml" # Path to test results (inside artifact .zip)
          reporter: java-junit # Format of test results
